function get_ui_resource()
{
    let table = [

       OPTIONS_THEME,
       'ctrl_options_theme',
       'menu_item',
       update_group_options,
       update_group_options,
       update_group_options,

       OPTIONS_EFFECT,
       'ctrl_options_effect',
       'menu_item',
       update_group_options,
       update_group_options,
       update_group_options,

       OPTIONS_RESOLUTION,
       'ctrl_options_resolution',
       'menu_item',
       update_group_options,
       update_group_options,
       update_group_options,

       THEME_DEFAULT,
       'ctrl_theme_default',
       'menu_item',
       null,
       update_group_theme,
       null,

       THEME_VAPORWAVE,
       'ctrl_theme_vaporwave',
       'menu_item',
       null,
       update_group_theme,
       null,

       THEME_THANOS,
       'ctrl_theme_thanos',
       'menu_item',
       null,
       update_group_theme,
       null,

       THEME_NIGHT,
       'ctrl_theme_night',
       'menu_item',
       null,
       update_group_theme,
       null,

       THEME_FIRE,
       'ctrl_theme_fire',
       'menu_item',
       null,
       update_group_theme,
       null,

       THEME_JURASSIC_BEACH,
       'ctrl_theme_jurassic_beach',
       'menu_item',
       null,
       update_group_theme,
       null,

       THEME_THE_LAST_FIGHT,
       'ctrl_theme_the_last_fight',
       'menu_item',
       null,
       update_group_theme,
       null,

       EFFECT_NONE,
       'ctrl_effect_none',
       'menu_item',
       null,
       update_group_effect,
       null,

       EFFECT_TRANSPARENT,
       'ctrl_effect_transparent',
       'menu_item',
       null,
       update_group_effect,
       null,

       EFFECT_RIPPLE,
       'ctrl_effect_ripple',
       'menu_item',
       null,
       update_group_effect,
       null,

       EFFECT_REVERSE_RIPPLE,
       'ctrl_effect_reverse_ripple',
       'menu_item',
       null,
       update_group_effect,
       null,

       EFFECT_DOUBLE_RIPPLE,
       'ctrl_effect_double_ripple',
       'menu_item',
       null,
       update_group_effect,
       null,

       EFFECT_DOUBLE_WAVE,
       'ctrl_effect_double_wave',
       'menu_item',
       null,
       update_group_effect,
       null,

       EFFECT_WAVE,
       'ctrl_effect_wave',
       'menu_item',
       null,
       update_group_effect,
       null,

       EFFECT_WAVEX2,
       'ctrl_effect_wavex2',
       'menu_item',
       null,
       update_group_effect,
       null,
 
       EFFECT_WAVEX4,
       'ctrl_effect_wavex4',
       'menu_item',
       null,
       update_group_effect,
       null,

       EFFECT_WAVEX8,
       'ctrl_effect_wavex8',
       'menu_item',
       null,
       update_group_effect,
       null,

       EFFECT_HALLUCINATION,
       'ctrl_effect_hallucination',
       'menu_item',
       null,
       update_group_effect,
       null,

       EFFECT_FLAMES,
       'ctrl_effect_flames',
       'menu_item',
       null,
       update_group_effect,
       null,

       EFFECT_REALITY_DISTORTION,
       'ctrl_effect_reality_distortion',
       'menu_item',
       null,
       update_group_effect,
       null,

       RESOLUTION_ULTRA,
       'ctrl_resolution_ultra',
       'menu_item',
       null,
       update_group_resolution,
       null,

       RESOLUTION_HIGH,
       'ctrl_resolution_high',
       'menu_item',
       null,
       update_group_resolution,
       null,

       RESOLUTION_MEDIUM_HIGH,
       'ctrl_resolution_medium_high',
       'menu_item',
       null,
       update_group_resolution,
       null,

       RESOLUTION_MEDIUM,
       'ctrl_resolution_medium',
       'menu_item',
       null,
       update_group_resolution,
       null,

       RESOLUTION_LOW,
       'ctrl_resolution_low',
       'menu_item',
       null,
       update_group_resolution,
       null,

       CTRL_SNAPSHOT,
       'ctrl_snapshot',
       'control',
       null,
       null,
       null,

       CTRL_GENERATE,
       'ctrl_generate',
       'control',
       null,
       null,
       null,

       CTRL_CANCEL,
       'ctrl_cancel',
       'control',
       null,
       null,
       null,

       CTRL_DOWNLOAD,
       'ctrl_download',
       'control',
       update_control_link,
       update_control_link,
       update_control_link,

       CTRL_CLOSE,
       'ctrl_close',
       'control',
       update_control_close,
       update_control_close,
       update_control_close,

       CTRL_OK,
       'ctrl_ok',
       'control',
       update_control_close,
       update_control_close,
       update_control_close,

       CTRL_WEBSITE,
       'ctrl_website',
       'control',
       update_control_website,
       update_control_website,
       update_control_website ];


    return table;
}


